[application]
name = "wt-skin-manager"

[bundle]
identifier = "com.slyvred.wt-skin-manager"
publisher = "Slyvred"
icon = ["assets/Imil-Sea-Crab.ico"]
resources = ["assets/fonts/CaskaydiaMonoNerdFont-Regular.ttf"]

[web.app]

# HTML title tag content
title = "wt-skin-manager"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
